namespace SchoolManagement.Model
{
    public class InventoryCategory { public int Id { get; set; } public int SchoolId { get; set; } public string Name { get; set; } = ""; public string? Description { get; set; } public bool IsActive { get; set; } = true; }
    public class InventoryVendor { public int Id { get; set; } public int SchoolId { get; set; } public string VendorName { get; set; } = ""; public string? ContactPerson { get; set; } public string Mobile { get; set; } = ""; public string? GstNumber { get; set; } public string? Email { get; set; } public string? Address { get; set; } public bool IsActive { get; set; } = true; }
    public class InventoryProduct
    {
        public int Id { get; set; } public int SchoolId { get; set; } public int CategoryId { get; set; }
        public string ProductCode { get; set; } = ""; public string ProductName { get; set; } = "";
        public string? Brand { get; set; } public string Unit { get; set; } = "Piece"; public string? HsnCode { get; set; }
        public decimal PurchasePrice { get; set; } public decimal SellingPrice { get; set; } public decimal GstPercent { get; set; }
        public decimal CurrentStock { get; set; } public decimal ReservedStock { get; set; } public decimal IssuedStock { get; set; }
        public decimal MinimumStock { get; set; } public string? Barcode { get; set; } public bool IsActive { get; set; } = true;
    }
    public class InventoryProductVariant { public int Id { get; set; } public int ProductId { get; set; } public string VariantName { get; set; } = ""; public string? Sku { get; set; } public string? Barcode { get; set; } public decimal CurrentStock { get; set; } public decimal ReservedStock { get; set; } public decimal PriceAdjustment { get; set; } public bool IsActive { get; set; } = true; }
    public class InventoryBook { public int Id { get; set; } public int ProductId { get; set; } public int SchoolId { get; set; } public int AcademicSessionId { get; set; } public int? ClassId { get; set; } public int? SectionId { get; set; } public int? SubjectId { get; set; } public string? Publisher { get; set; } public string? Edition { get; set; } public string? Isbn { get; set; } }
    public class InventoryKit { public int Id { get; set; } public int SchoolId { get; set; } public int AcademicSessionId { get; set; } public int? ClassId { get; set; } public string KitName { get; set; } = ""; public string KitType { get; set; } = "Book"; public decimal DiscountAmount { get; set; } public bool IsActive { get; set; } = true; }
    public class InventoryKitItem { public int Id { get; set; } public int KitId { get; set; } public int ProductId { get; set; } public int? ProductVariantId { get; set; } public decimal Quantity { get; set; } }
    public class InventoryPurchaseOrder { public int Id { get; set; } public int SchoolId { get; set; } public int VendorId { get; set; } public string PoNumber { get; set; } = ""; public DateTime PurchaseDate { get; set; } public string? InvoiceNumber { get; set; } public string Status { get; set; } = "Draft"; public decimal TotalAmount { get; set; } }
    public class InventoryPurchaseOrderItem { public int Id { get; set; } public int PurchaseOrderId { get; set; } public int ProductId { get; set; } public int? ProductVariantId { get; set; } public decimal Quantity { get; set; } public decimal Rate { get; set; } public decimal GstPercent { get; set; } public decimal Discount { get; set; } }
    public class InventoryStockTransaction { public long Id { get; set; } public int SchoolId { get; set; } public int ProductId { get; set; } public int? ProductVariantId { get; set; } public string TransactionType { get; set; } = "IN"; public decimal Quantity { get; set; } public string ReferenceType { get; set; } = "Manual"; public int? ReferenceId { get; set; } public DateTime TransactionDate { get; set; } = DateTime.Now; public string? Remarks { get; set; } }
    public class InventoryStudentOrder { public int Id { get; set; } public int SchoolId { get; set; } public int AcademicSessionId { get; set; } public int StudentId { get; set; } public string OrderNumber { get; set; } = ""; public DateTime OrderDate { get; set; } = DateTime.Now; public string Status { get; set; } = "Pending"; public decimal TotalAmount { get; set; } public decimal PaidAmount { get; set; } }
    public class InventoryStudentOrderItem { public int Id { get; set; } public int StudentOrderId { get; set; } public int ProductId { get; set; } public int? ProductVariantId { get; set; } public decimal Quantity { get; set; } public decimal UnitPrice { get; set; } public decimal GstPercent { get; set; } public decimal Discount { get; set; } }
    public class InventoryPayment { public int Id { get; set; } public int StudentOrderId { get; set; } public string ReceiptNumber { get; set; } = ""; public decimal Amount { get; set; } public DateTime PaymentDate { get; set; } = DateTime.Now; public string PaymentMode { get; set; } = "Cash"; public string? ReferenceNumber { get; set; } }
    public class InventoryReturn { public int Id { get; set; } public int SchoolId { get; set; } public int StudentOrderId { get; set; } public string ReturnNumber { get; set; } = ""; public DateTime ReturnDate { get; set; } = DateTime.Now; public string Reason { get; set; } = ""; public decimal RefundAmount { get; set; } }
    public class InventoryReturnItem { public int Id { get; set; } public int ReturnId { get; set; } public int ProductId { get; set; } public int? ProductVariantId { get; set; } public decimal Quantity { get; set; } public string Condition { get; set; } = "Good"; public bool Restock { get; set; } = true; }
}
